version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: python:3.6.0
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Dependencies
          command: pip install -r requirements/dev.txt
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Run Tests
          command: python manage.py test
      - run:
            name: trigger builds
            command: |
              # this function will liekly get built in into the circleci cli 
              function trigger_job() {
                job_name=$1
                curl -u ${CIRCLE_API_TOKEN}: \
                  -d build_parameters[CIRCLE_JOB]=${job_name} \
                  -d revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/keybits/circulate/tree/$CIRCLE_BRANCH
              }      
              trigger_job build-python27
              trigger_job build-python35
              trigger_job build-python36


      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - deploy:
          name: Echo
          command: echo "I would deploy here"
      #    name: Deploy Master to Heroku
      #    command: |
      #      if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #        git push heroku master
      #        heroku run python manage.py deploy
      #        heroku restart
      #      fi


  # here are our jobs with different Ruby versions
  build-python27:
       docker:
         - image: python:2.7.13 
       working_directory: ~/circulate
       steps:
         - run: echo "hello python 2.7.13"
  
  build-python35:
       docker:
         - image: python:3.5.3 
       working_directory: ~/circulate
       steps:
         - run: echo "hello python 3.5.3"
  
  build-python36:
       docker:
         - image: python:3.6.0
       working_directory: ~/circulate
       steps:
         - run: echo "hello python 3.6.0"