version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: export TAG=build-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} && echo $TAG
      - run:
        name: Download Selenium and geckodriver
        command: |
          curl -O http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar
          curl -L https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz | tar xz
          chmod +x geckodriver
      - run:
        name: Start Selenium
        command: |
          java -jar -Dwebdriver.gecko.driver=./geckodriver selenium-server-standalone-3.0.1.jar -log selenium.log
          background: true
      - restore_cache:
          key: deps3-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run: echo $CIRCLE_TAG
      - run: echo $TAG
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - save_cache:
          key: deps3-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      - run: mv selenium.log selenium_log.txt
      - store_artifacts:
          path: test-reports/
          destination: tr1
          path: selenium_log.txt
          destination: selenium
      - store_test_results:
          path: test-reports/
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - deploy:
          name: Echo
          command: echo "I would deploy here"
      #    name: Deploy Master to Heroku
      #    command: |
      #      if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #        git push heroku master
      #        heroku run python manage.py deploy
      #        heroku restart
      #      fi
